eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      #efaultZone: ${EUREKA_URI:http://52.151.226.196:8761/eureka}
  instance:
    #hostname: localhost
    preferIpAddress: true
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-ms
          #uri: http://20.85.204.185:8002
          uri: http://localhost:8002
        #uri: lb://customer-ms
          predicates:
            - Path=/api/v1/customers/**